version: '3.8'

services:
  # -------------------------
  # Neo4j
  # -------------------------
  neo4j:
    image: neo4j:5
    container_name: neo4j-belden
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  # -------------------------
  # PostgreSQL
  # -------------------------
  postgres:
    image: postgres:16
    container_name: belden-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=belden
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  kafka_data:
  neo4j_data:
  postgres_data:
